### ISSUE TITLE
Avoid use of == and != in "tests/solidity/test/ERC20.js"

### ISSUE THREAD

**Issue by warifp** [SigmaGmbH/swisstronik-chain#13]
### 1. **Bug/Vulnerability Description** 
It is considered good practice to use the type-safe equality operators === and !== instead of their regular counterparts == and !=.

The strict equality operators (=== and !==) use the strict equality comparison algorithm to compare two operands.

### 2. **Hardware and Software Specifications** 
- OS Name & version Ubuntu 20.04
- CPU Name & Brand linux/amd64
- Go version 1.20.5

### 3. **Steps to Reproduce** 
Sample BAD PRACTICE AND RECOMMENDED
BAD PRACTICE
```
a == b
foo == true
bananas != 1
value == undefined
typeof foo == 'undefined'
'hello' != 'world'
0 == 0
true == true
foo == null
```

RECOMMENDED
```
a === b
foo === true
bananas !== 1
value === undefined
typeof foo === 'undefined'
'hello' !== 'world'
0 === 0
true === true
foo === null
```

### 4. **Impact Analysis** 

- If the operands are of different types, return false.
- If both operands are objects, return true only if they refer to the same object.
- If both operands are null or both operands are undefined, return true.
- If either operand is NaN, return false.
- Otherwise, compare the two operand's values:
Numbers must have the same numeric values. +0 and -0 are considered to be the same value.
Strings must have the same characters in the same order.
Booleans must be both true or both false.

The most notable difference between this operator and the equality (==) operator is that if the operands are of different types, the == operator attempts to convert them to the same type before comparing.

### 6. **Choose the Right Label** 
operators, strict, quality

## Swisstronik internal use only
- [x] Not duplicate issue
- [x] Appropriate labels applied

**Comment by santiagotrujilloz** [comment]
Hi @warifp thanks for submitting your feedback!
Unfortunately, this script is just for testing purposes and it doesn't fall under the scope of the Bug bounty.
