### ISSUE TITLE
Unused code in "x/swisstronik/client/cli/tx.go"

### ISSUE THREAD

**Issue by warifp** [SigmaGmbH/swisstronik-chain#14]
### 1. **Bug/Vulnerability Description** 
It is recommended to keep the codebase clean by removing unused code.

### 2. **Hardware and Software Specifications** 
- OS Name & version Ubuntu 20.04
- CPU Name & Brand linux/amd64
- Go version 1.20.5

### 3. **Steps to Reproduce** 
```
const (
	flagPacketTimeoutTimestamp = "packet-timeout-timestamp"
	listSeparator              = ","
)
```

### 4. **Impact Analysis** 
This part of the code has not been used anywhere in the project and is not exported. Maybe it was mistakenly left behind while refactoring or was intended to be used somewhere but remained unused by mistake..

### 5. **Code Fix Submission** 
Delete un-used code

### 6. **Choose the Right Label** 
clean-code

## Swisstronik internal use only
- [x] Not duplicate issue
- [x] Appropriate labels applied

**Comment by MikkySnow** [comment]
Hello, thanks for submitting your issue. `x/swisstronik` module is reserved for future usage, so now it's unused. For sure, we will clean up code of this module, once it will be used or will remove this module if there won't be any need in the module
