### ISSUE TITLE
BUG IN SGX 

### ISSUE THREAD

**Issue by Jaksomplak** [SigmaGmbH/swisstronik-chain#2]
For now, you can use any Intel CPU that supports SGX through SPS, but not all Intel CPUs can be used to support SGX through SPS

**Comment by santiagotrujilloz** [comment]
Hey @Jaksomplak !
Could you please use our [issue template](https://github.com/SigmaGmbH/swisstronik-chain/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) to resubmit this issue? It helps us get all the details needed to assist you better. 
Thank you!
