### ISSUE TITLE
Install rustup by running have a bug 

### ISSUE THREAD

**Issue by Jaksomplak** [SigmaGmbH/swisstronik-chain#3]
di prosses Install rustup by running node , curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | .sh
source "$HOME/.cargo/env", there was an error in inputting this

**Comment by santiagotrujilloz** [comment]
Hey @Jaksomplak !
Could you please use our [issue template](https://github.com/SigmaGmbH/swisstronik-chain/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) to resubmit this issue? It helps us get all the details needed to assist you better.
Thank you!
