### ISSUE TITLE
ICA Controller route not found when registering Interchain Account

### ISSUE THREAD

**Issue by arifintahu** [SigmaGmbH/swisstronik-chain#61]
### 1. **Bug/Vulnerability Description** 
Unable to register an Interchain  Account from ICA Controller Module.

### 2. **Hardware and Software Specifications** 
WSL Ubuntu 22

### 3. **Steps to Reproduce** 
1. Run hermes relayer between `Swisstronik Testnet` with `Cosmos Hub Testnet`
2. Create relayer connection 
CMD: `hermes create connection --a-chain swisstronik_1291-1 --b-chain theta-testnet-001`
![image](https://github.com/SigmaGmbH/swisstronik-chain/assets/20294658/a1114463-40e0-463b-b1bf-c398305b5d0b)
And we got `connection-0` for swisstronik testnet
3. Register Interchain Account using `connection-0`
CMD: `swisstronikcli tx interchain-accounts controller register connection-0 --from test2 --gas-prices 7uswtr -y`
And the transaction will fail like in this one [Tx Hash](https://explorer-cosmos.testnet.swisstronik.com/swisstronik/tx/1E67589A8E98E6357534175FBA0FD4882CDA4C44B2D48F83AC40F3225C3E541E) due to route not found for module ica controller
![image](https://github.com/SigmaGmbH/swisstronik-chain/assets/20294658/867b7f55-3d84-462c-ae0c-d109f6cf0fcc)

### 4. **Impact Analysis** 
Swisstronik testnet is unable to register an interchain account due to the ICA Controller module route not found. It happens due to ICA Controller module hasn’t registered on IBC Router yet, as seen [below](https://github.com/SigmaGmbH/swisstronik-chain/blob/010fc2a1885e104e466bbec55e49a37f4022b6c5/app/app.go#L603)
![image](https://github.com/SigmaGmbH/swisstronik-chain/assets/20294658/99fe41ca-3b17-4147-aae0-9384f1380d61)

### 5. **Code Fix Submission** 
- If ICA Controller is important for swisstronik then add the IBC route `AddRoute(icacontrollertypes.SubModuleName, icaControllerStack)`
- But if ICA Controller is not aligned with swisstronik use cases then the ICA Controller module can be disabled

### 6. **Choose the Right Label** 
`bug`

### 7. **Additional Context** 
[Tx History Register ICA](https://explorer-cosmos.testnet.swisstronik.com/swisstronik/tx/1E67589A8E98E6357534175FBA0FD4882CDA4C44B2D48F83AC40F3225C3E541E)

____

Thank you for contributing to the improvement of our project!👨‍💻👩‍💻
____

## Swisstronik internal use only
- [ ] Not duplicate issue
- [ ] Appropriate labels applied

**Comment by MikkySnow** [comment]
Fixed with https://github.com/SigmaGmbH/swisstronik-chain/pull/62
