### ISSUE TITLE
There was a problem when I was going to do the "make install" command in the terminal

### ISSUE THREAD

**Issue by OneNov0209** [SigmaGmbH/swisstronik-chain#7]
![Screenshot_2023-07-28-14-25-12-553-edit_com server auditor ssh client](https://github.com/SigmaGmbH/swisstronik-chain/assets/95606017/a4c94c18-072d-46b7-aa7a-85b3c927ae5b)
## Bug Report Template

Please use this template to report bugs or vulnerabilities. Please fill out all the sections below:

### 1. **Bug/Vulnerability Description** 
Clearly state and describe the identified bug or vulnerability.

### 2. **Hardware and Software Specifications** 
- OS Name & version
- CPU Name & Brand
- Go version
- Rust version
- SGX version (optional)
- \[ \] Docker environment

### 3. **Steps to Reproduce** 
Provide clear and concise instructions to reproduce the reported bug or vulnerability.

### 4. **Impact Analysis** 
Analyze the potential consequences of the bug or vulnerability on users, developers, and the organization.

### 5. **Code Fix Submission** 
(Optional) If you have a suggestion for fixing the bug or vulnerability, provide a code fix or a proposed solution.

### 6. **Choose the Right Label** 
Choose the suitable label/s that represents the nature of the issue being resolved, indicating its specific category and severity of the vulnerability

### 7. **Additional Context** 
(Optional)Share any relevant context, screenshots, logs, or error messages that can facilitate problem-solving and comprehensive understanding.

____

Thank you for contributing to the improvement of our project!👨‍💻👩‍💻
____

## Swisstronik internal use only
- [x] Not duplicate issue
- [x] Appropriate labels applied

**Comment by MikkySnow** [comment]
Hello, thanks for submitting your issue. Could you provide all steps that you did from `git clone` to `make install`?

**Comment by delneg** [comment]
You have to clone recursively, with submodules
`git clone --recursive https://github.com/SigmaGmbH/swisstronik-chain`

**Comment by OneNov0209** [comment]
i did this step: git clone https://github.com/SigmaGmbH/swisstronik-chain swisstronik
cd swisstronik
git checkout v0.1.0
make install


what I'm asking is, when I do git clone swisstronik-chain, then "cd swisstronik" won't go into that file, because the git clone command is swisstronik-chain, so after I command git clone, then I command cd swisstronik  the chains work

**Comment by OneNov0209** [comment]
![Screenshot_2023-07-28-18-55-30-517-edit_com server auditor ssh client](https://github.com/SigmaGmbH/swisstronik-chain/assets/95606017/e62db5ee-95f5-46ca-8706-05d5c137225b)
And this not work

**Comment by OneNov0209** [comment]
can you provide a solution?  because I followed the tutorial in this doc
https://swisstronik.gitbook.io/swisstronik-docs/swisstronik-testnet/node-installation-guide

**Comment by delneg** [comment]
The docs have been update.
As stated previously, you have clone recursively with submodules:
git clone --recursive https://github.com/SigmaGmbH/swisstronik-chain swisstronik

Alternatively, you can do `make init`

**Comment by harismanciripto111** [comment]
It seems like this is the same problem happening with me, what version of rustc did you install?

**Comment by harismanciripto111** [comment]
https://github.com/SigmaGmbH/swisstronik-chain/issues/10

you can see my issue

**Comment by OneNov0209** [comment]
> 

Ok I will try

**Comment by OneNov0209** [comment]
> Dokumen telah diperbarui. Seperti yang dinyatakan sebelumnya, Anda memiliki klon secara rekursif dengan submodul: git clone --recursive https://github.com/SigmaGmbH/swisstronik-chain swisstronik
> 
> Alternatifnya, Anda bisa melakukannya`make init`

I have tried to do what you suggested, but the result is still an error, sir, like this
![Screenshot_2023-07-30-19-01-31-860-edit_com server auditor ssh client](https://github.com/SigmaGmbH/swisstronik-chain/assets/95606017/c1079549-b2d0-4abc-8b36-1593346d6c2f)
![Screenshot_2023-07-30-19-01-53-472-edit_com server auditor ssh client](https://github.com/SigmaGmbH/swisstronik-chain/assets/95606017/4ece9c04-6c93-451f-9468-ff69e747971c)

**Comment by harismanciripto111** [comment]
> > Dokumen telah diperbarui. Seperti yang dinyatakan sebelumnya, Anda memiliki klon secara rekursif dengan submodul: git clone --recursive https://github.com/SigmaGmbH/swisstronik-chain swisstronik
> > Alternatifnya, Anda bisa melakukannya`make init`
> 
> Saya sudah mencoba melakukan apa yang Anda sarankan, tetapi hasilnya masih kesalahan, Pak, seperti ini ![Screenshot_2023-07-30-19-01-31-860-edit_com Server Auditor SSH Client](https://user-images.githubusercontent.com/95606017/257047257-c1079549-b2d0-4abc-8b36-1593346d6c2f.jpg) ![Screenshot_2023-07-30-19-01-53-472-edit_com Server Auditor SSH Client](https://user-images.githubusercontent.com/95606017/257047259-4ece9c04-6c93-451f-9468-ff69e747971c.jpg)

SGX already install?
try to sudo $(which sgx-detect) and screenshot again send here, I want to see it

**Comment by OneNov0209** [comment]
> > > Dokumen telah diperbarui. Seperti yang dinyatakan sebelumnya, Anda memiliki klon secara rekursif dengan submodul: git clone --recursive https://github.com/SigmaGmbH/swisstronik-chain swisstronik
> > > Alternatifnya, Anda bisa melakukannya`make init`
> > 
> > 
> > Saya sudah mencoba melakukan apa yang Anda sarankan, tetapi hasilnya masih kesalahan, Pak, seperti ini ![Screenshot_2023-07-30-19-01-31-860-edit_com Server Auditor SSH Client](https://user-images.githubusercontent.com/95606017/257047257-c1079549-b2d0-4abc-8b36-1593346d6c2f.jpg) ![Screenshot_2023-07-30-19-01-53-472-edit_com Server Auditor SSH Client](https://user-images.githubusercontent.com/95606017/257047259-4ece9c04-6c93-451f-9468-ff69e747971c.jpg)
> 
> SGX already install? try to sudo $(which sgx-detect) and screenshot again send here, I want to see it ![image](https://user-images.githubusercontent.com/105085410/257047527-2b92f4c7-e279-423e-9057-ca2a8a22900e.png) should come up with output like this

![Screenshot_2023-07-30-19-23-58-305-edit_com server auditor ssh client](https://github.com/SigmaGmbH/swisstronik-chain/assets/95606017/665bba70-2d48-413e-86b4-82a59ac3ebd4)
Like this

**Comment by OneNov0209** [comment]
![Screenshot_2023-07-30-19-29-26-314-edit_com server auditor ssh client](https://github.com/SigmaGmbH/swisstronik-chain/assets/95606017/dea87f83-3d2d-4b3f-b868-68f41f0fdb46)
I try install this

**Comment by OneNov0209** [comment]
![Screenshot_2023-07-30-21-01-24-487-edit_com server auditor ssh client](https://github.com/SigmaGmbH/swisstronik-chain/assets/95606017/21250f17-64bd-4eff-ac6a-9d3bba4240f1)
How to fix?

**Comment by MikkySnow** [comment]
Try `sudo sgx-detect`

**Comment by OneNov0209** [comment]
> Try `sudo sgx-detect`

![Screenshot_2023-07-31-22-45-27-812-edit_com server auditor ssh client](https://github.com/SigmaGmbH/swisstronik-chain/assets/95606017/0e57d2fa-50a5-4386-8840-09ae327693cd)
![Screenshot_2023-07-31-22-45-00-465-edit_com server auditor ssh client](https://github.com/SigmaGmbH/swisstronik-chain/assets/95606017/94132d8a-d1cf-439c-9fec-e4177cbbb215)
I've installed the sgx, but the results are still the same

**Comment by delneg** [comment]
Try `sudo ./root/.cargo/bin/sgx-detect`

**Comment by OneNov0209** [comment]
> 

![Uploading Screenshot_2023-07-31-22-49-55-125-edit_com.server.auditor.ssh.client.jpg…]()

**Comment by MikkySnow** [comment]
Could you upload again your screenshots?

**Comment by OneNov0209** [comment]
> Could you upload again your screenshots?

![Uploading Screenshot_2023-08-02-19-59-21-710-edit_com.server.auditor.ssh.client.jpg…]()

**Comment by OneNov0209** [comment]
![Uploading Screenshot_2023-08-02-22-42-33-581-edit_com.server.auditor.ssh.client.jpg…]()

I run inside the root

**Comment by OneNov0209** [comment]
![Uploading Screenshot_2023-08-02-22-46-04-350-edit_com.server.auditor.ssh.client.jpg…]()

**Comment by MikkySnow** [comment]
I cannot see your screenshots, could you send text response?

**Comment by OneNov0209** [comment]
root@vmi1031685:~# whereis sgx-detect
sgx-detect:

Just this sir

**Comment by MikkySnow** [comment]
Seems like `sgx-detect` was not installed or not added to PATH. Could you reinstall it by running
```
cargo install sgxs-tools
```

and provide the output

**Comment by OneNov0209** [comment]
![Screenshot_2023-08-03-09-01-55-603-edit_com server auditor ssh client](https://github.com/SigmaGmbH/swisstronik-chain/assets/95606017/26e82a63-d636-463b-b10f-f5a5ef9d7649)
How about this?

**Comment by MikkySnow** [comment]
Did you add `/root/.cargo/bin` to PATH?

**Comment by harismanciripto111** [comment]
check your vps specification sir, you need intel cpu for install SGX

**Comment by MikkySnow** [comment]
Is it related to this issue?

You have to use Intel CPUs with SGX only if you want to run `swisstronikd` in production mode. If you want to use it for test purposes, you can build `swisstronikd` in simulation mode

**Comment by OneNov0209** [comment]
> 

![Screenshot_2023-08-03-22-29-40-641-edit_com server auditor ssh client](https://github.com/SigmaGmbH/swisstronik-chain/assets/95606017/1889e650-ade9-49b1-b0c8-a62e5b9100b7)

Like this sir

**Comment by MikkySnow** [comment]
So `sgx-detect` is not included in PATH. Please update your PATH env variable with `/root/.cargo/bin` directory. You can find comprehensive guide how to do it here: https://linuxize.com/post/how-to-add-directory-to-path-in-linux/

**Comment by OneNov0209** [comment]
> So `sgx-detect` is not included in PATH. Please update your PATH env variable with `/root/.cargo/bin` directory. You can find comprehensive guide how to do it here: https://linuxize.com/post/how-to-add-directory-to-path-in-linux/

Ok thanks sir,, i will try again

**Comment by harismanciripto111** [comment]
> 

yes

**Comment by MikkySnow** [comment]
But it should be possible to build `swisstronikd` in simulation mode. This mode does not require SGX-compatible hardware, but cannot be used in production

**Comment by OneNov0209** [comment]
ok sir, I understand, thanks for the support
