### ISSUE TITLE
There was a problem when I was going to do the "git clone" command in the terminal

### ISSUE THREAD

**Issue by Alfonova-Node** [SigmaGmbH/swisstronik-chain#8]
can not git clone swisstronik because username not found.

![image](https://github.com/SigmaGmbH/swisstronik-chain/assets/85473027/684a4592-e693-4732-9bcd-1d2ed1cdbfd7)

**Comment by MikkySnow** [comment]
Hello, thanks for submitting your issue. There was a broken link to the repo in documentation, try this repository instead https://github.com/SigmaGmbH/swisstronik-chain.git

**Comment by delneg** [comment]
git clone --recursive https://github.com/SigmaGmbH/swisstronik-chain
